import numpy as np

REVERSE_INTEGER_ENCODING = np.array(["!", "A", "C", "G", "T"])
INTEGER_ENCODING_MAP = {}

for i in range(len(REVERSE_INTEGER_ENCODING)):
    INTEGER_ENCODING_MAP[REVERSE_INTEGER_ENCODING[i]] = i

BASES = INTEGER_ENCODING_MAP.copy()
BASES.pop("!")

ONE_HOT_ENCODING = np.zeros((len(REVERSE_INTEGER_ENCODING), len(REVERSE_INTEGER_ENCODING)))
ONE_HOT_QUALITY_ENCODING = np.zeros((len(REVERSE_INTEGER_ENCODING), len(REVERSE_INTEGER_ENCODING) + 1))
for i in range(len(ONE_HOT_ENCODING)):
    ONE_HOT_ENCODING[i][i] = 1
    ONE_HOT_QUALITY_ENCODING[i][i] = 1
